# Generated by Django 2.2.14 on 2020-07-12 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpauth', '0002_auto_20190818_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Esse email já existe.'}, help_text='O email será usado para acessar o sistema e enviar informações', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Os grupos a que este usuário pertence. Um usuário receberá todas as permissões concedidas a cada um dos seus grupos', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas para este usuário.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='Permissões de usuário'),
        ),
    ]
